# Generated by Django 6.0 on 2026-02-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(help_text='Example: P1, Break, Lunch', max_length=20)),
                ('is_break', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_assembly', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['year', 'term'],
                'unique_together': {('year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.classlevel')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.stream')),
            ],
            options={
                'unique_together': {('level', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elective_group', models.CharField(blank=True, choices=[('Languages', 'Languages'), ('Religions', 'Religions'), ('Vocationals', 'Vocationals')], max_length=20, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red'), ('brown', 'Brown'), ('teal', 'Teal'), ('gray', 'Gray')], default='gray', max_length=20, unique=True)),
                ('levels', models.ManyToManyField(to='timetable_planner_app.schoolclass')),
                ('teachers', models.ManyToManyField(to='timetable_planner_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='LessonInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.academicterm')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.timeslot')),
            ],
            options={
                'unique_together': {('teacher', 'day', 'time_slot', 'term')},
            },
        ),
    ]
