# Generated by Django 6.0 on 2026-02-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_planner_app', '0002_school_schoolclass_school_teacher_school_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red'), ('brown', 'Brown'), ('teal', 'Teal'), ('gray', 'Gray')], default='gray', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.school'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_planner_app.school'),
        ),
    ]
